name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read
  
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Baixa código
        uses: actions/checkout@v2
      - name: Instala dependências
        run: mvn package -B -ntp -Dmaven.test.skip=true
      - name: Avalia respostas
        uses: education/autograding@v1

